"""No real datasets are opened or generated by these policy checks."""
import os
from pathlib import Path
import sys
import unittest
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from runtime import require_github_hosted_runner


class RemoteStoragePolicy(unittest.TestCase):
    def test_local_execution_refused(self):
        with patch.dict(os.environ, {}, clear=True):
            with self.assertRaises(RuntimeError):
                require_github_hosted_runner()

    def test_self_hosted_execution_refused(self):
        with patch.dict(os.environ, {"GITHUB_ACTIONS": "true", "RUNNER_ENVIRONMENT": "self-hosted"}, clear=True):
            with self.assertRaises(RuntimeError):
                require_github_hosted_runner()


if __name__ == "__main__":
    unittest.main()
